### ISSUE TITLE
Bug - plugin is not compatible with docker running in buildkit mode

### ISSUE THREAD

**Issue by Nugs** [marcuslonnberg/sbt-docker#106]
Background
---

Running docker in buildkit mode `DOCKER_BUILDKIT=1 docker build .` we can increase performance of our docker builds (https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds)

This can be enabled for the docker daemon by setting the feature in `/etc/docker/daemon.json`:

```
{ "features": { "buildkit": true } }
```

However, the output of docker changes under buildkit in 2 significant ways:

* Output is no longer to console (STDOUT) but is reported via STDERR
* The formatting of lines crucial to the plugin (sha hash of build image) differs

Impact
---

With buildkit enabled, docker performs the build as expected but the regular expression matching in `DockerBuild` no longer matches the `^Successfully built ([0-9a-f]+)$` pattern. As a result, the ImageId cannot be established and the task fails.

Proposed Resolution
---

The new pattern required for buildkit would be similar to: `^.*writing image sha256:([0-9a-f]+).*done$` this can be added alongside the non-buildkit regex so that compatibility is maintained between both modes of operation.

However, adding this in isolation will not resolve the situation due to the other change - that output is no longer piped to STDOUT. The functionality around the processLogger needs to be amended to capture stdout + stderr data and process on _that_ rather than on the Stream returned from the `Process`. This too would be backward compatible as a combined STDOUT/ERR data would be matchable for both buildkit and legacy mode operation.

**Comment by marcuslonnberg** [comment]
A fix for this have now been released in version 1.6.0.

There is now a section in the readme about it: https://github.com/marcuslonnberg/sbt-docker#buildkit-support
