### ISSUE TITLE
dockerBuildAndPush and dockerPush could return image digest

### ISSUE THREAD

**Issue by RayRoestenburg** [marcuslonnberg/sbt-docker#108]
It would be great if `dockerBuildAndPush`, and `dockerPush`, could return the image digest of the image that was pushed.

Maybe have it return something like: 
```
final case class ImageDigest(digest: String)
```
Currently `DockerPush` does not process the stdout, would be great if it did and find the
```<tag>: digest: sha256:<digest> size: <size>``` lines.

**Comment by marcuslonnberg** [comment]
Released in https://github.com/marcuslonnberg/sbt-docker/releases/tag/v1.8.0.
