### ISSUE TITLE
This way vs vanilla Dockerfile

### ISSUE THREAD

**Issue by thestephenstanton** [marcuslonnberg/sbt-docker#116]
What are the benefits of building an image this way (all these sbt plugins) vs doing something like this: https://medium.com/@yzhong.cs/getting-started-with-docker-scala-sbt-d91f8ac22f5f

I ask because all of this is just so complicated. No instructions that I have found have been easy or straightforward for just building a simple image.

**Comment by marcuslonnberg** [comment]
It all depends on your preferences, skills and setup.

sbt-docker is especially good if you prefer to perform every build step within sbt. As well if you want to use dynamic information from sbt settings or tasks, such as file output paths.
