### ISSUE TITLE
Private registry

### ISSUE THREAD

**Issue by rafael** [marcuslonnberg/sbt-docker#18]
Hi all -

Is there a way to push to private registries using sbt-docker?

**Comment by marcuslonnberg** [comment]
Hi!

Yes it is possible. If you have authenticated to your private registry with `docker login ...`, you should just be able to push to it from sbt-docker (with `dockerPush` and `dockerBuildAndPush`).

But you need to set the registry property in the image name:
```
imageName in docker := {
	ImageName(
	  registry = Some("registry.company.com:5000"),
	  repository = "abc")
}
```
or
`imageName in docker := ImageName("registry.company.com:5000/abc")`
