### ISSUE TITLE
2.11 Release

### ISSUE THREAD

**Issue by adamdecaf** [marcuslonnberg/sbt-docker#20]
It would be nice to have a release out for 2.11. I'm trying to get this project to cross build. If ti works out I'll open a PR.

**Comment by adamdecaf** [comment]
It looks like this is a much deeper issue: https://github.com/sbt/sbt/issues/1813

**Comment by marcuslonnberg** [comment]
Since there are no 2.11 releases of sbt available I will close this.
Feel free to open a new issue when such releases exist.
