### ISSUE TITLE
classpath issue with dockerSettingsAutoPackage ?

### ISSUE THREAD

**Issue by joune** [marcuslonnberg/sbt-docker#21]
Hi,

First, thumbs up! I've just discovered sbt-docker and I love the idea and simplicity! 

Now I've tried packaging a little spray application with 

        dockerSettingsAutoPackage("dockerfile/java", Seq(8080))

It creates the image without error, but when I try to run it, I get a NoClassDefFoundError. 
And "docker inspect" shows this:

        "Entrypoint": [
            "java",
            "-cp",            "/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/libs:/app/server_2.11-0.1.jar",
            "ap.test.Server"
        ],

It looks like the artifact names are missing from the classpath.

Note: I've also tried copying the sample from package-spray, but sbt complains on:
        
        error: not found: value docker
        docker <<= docker.dependsOn(Keys.`package`.in(Compile, packageBin))

thanks for the support .. and sorry if i'm doing something obviously wrong!

**Comment by marcuslonnberg** [comment]
Hi,

Thanks for reporting this issue.
Apperently `dockerSettingsAutoPackage` was faulty in the latest version.
Will release a new version with the fix shortly.
