### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by MasseGuillaume** [marcuslonnberg/sbt-docker#24]
on linux, the task `docker` fails because it's not run as root

```
[info] time="2015-03-19T16:12:18-04:00" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/build?dockerfile=Dockerfile&rm=1&t=: dial unix /var/run/docker.sock: permission denied" 
[info] Sending build context to Docker daemon 
```

**Comment by suhailshergill** [comment]
@MasseGuillaume what are the group permissions on ``/var/run``? perhaps the user needs to be run to specific group.

**Comment by nightscape** [comment]
You probably want to add your user to the docker group:
https://docs.docker.com/installation/ubuntulinux/#giving-non-root-access

**Comment by MasseGuillaume** [comment]
ty
