### ISSUE TITLE
tag for version 1.0.0 missing

### ISSUE THREAD

**Issue by timoreimann** [marcuslonnberg/sbt-docker#25]
It seems like version 1.0.0 of the plugin was released a few days ago ([maven.org link](http://search.maven.org/#artifactdetails%7Cse.marcuslonnberg%7Csbt-docker%7C1.0.0%7Cjar)). However, a corresponding git tag is missing for that release; the latest that can be found is still 0.5.2.

Could you add and push the tag so that looking up the code for a particular version in git is possible?

Thanks.

**Comment by marcuslonnberg** [comment]
I tagged it locally but forgot to push the tag. It's now fixed.
