### ISSUE TITLE
build marked as error when it's actually successful

### ISSUE THREAD

**Issue by jcrobak** [marcuslonnberg/sbt-docker#3]
I'm seeing the following:

```
[info] Successfully built :hash1
[info] Removing intermediate container :hash2
java.lang.RuntimeException: Could not parse image id
    at scala.sys.package$.error(package.scala:27)
    at sbtdocker.DockerBuilder$.buildImage(DockerBuilder.scala:87)
    at sbtdocker.DockerBuilder$.apply(DockerBuilder.scala:23)
    at sbtdocker.Plugin$$anonfun$baseDockerSettings$1.apply(Plugin.scala:27)
    at sbtdocker.Plugin$$anonfun$baseDockerSettings$1.apply(Plugin.scala:22)
    at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
    at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
[error] (*:docker) Could not parse image id
```

Looks like the code to parse the image id fails if there's a "removing intermediate container" line after "successfully built" since it only looks at the very last line of output: https://github.com/marcuslonnberg/sbt-docker/blob/master/src/main/scala/sbtdocker/DockerBuilder.scala#L82

I'm only seeing this transiently.

**Comment by elonybear** [comment]
Hi @marcuslonnberg, I'm experiencing this issue as well, on version 1.3.8. Do you know of a fix?

```
[info] #13 writing image sha256:ea4317746ead7d49f458df4f58a6d94625d99a8c60716ecaa2581a3ecc7121c6 done
[info] #13 DONE 1.8s
[error] java.lang.RuntimeException: Could not parse image id
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbtdocker.DockerBuild$.build(DockerBuild.scala:99)
[error] 	at sbtdocker.DockerBuild$.buildAndTag(DockerBuild.scala:72)
[error] 	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:45)
[error] 	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:24)
[error] 	at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$1(DockerSettings.scala:17)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (orion-feature-pipeline / docker) Could not parse image id
[error] Total time: 14 s, completed Oct 26, 2020 8:09:59 AM
```

**Comment by ukudtarkar** [comment]
> Hi @marcuslonnberg, I'm experiencing this issue as well, on version 1.3.8. Do you know of a fix?
> 
> ```
> [info] #13 writing image sha256:ea4317746ead7d49f458df4f58a6d94625d99a8c60716ecaa2581a3ecc7121c6 done
> [info] #13 DONE 1.8s
> [error] java.lang.RuntimeException: Could not parse image id
> [error] 	at scala.sys.package$.error(package.scala:30)
> [error] 	at sbtdocker.DockerBuild$.build(DockerBuild.scala:99)
> [error] 	at sbtdocker.DockerBuild$.buildAndTag(DockerBuild.scala:72)
> [error] 	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:45)
> [error] 	at sbtdocker.DockerBuild$.apply(DockerBuild.scala:24)
> [error] 	at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$1(DockerSettings.scala:17)
> [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
> [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
> [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
> [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
> [error] 	at sbt.Execute.work(Execute.scala:290)
> [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
> [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error] 	at java.lang.Thread.run(Thread.java:748)
> [error] (orion-feature-pipeline / docker) Could not parse image id
> [error] Total time: 14 s, completed Oct 26, 2020 8:09:59 AM
> ```

Which version of sbt-docker plugin you are using? I was running into same issue with version `1.5.0`. It seem to work `1.8.0` though.
`
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.8.0")
`
