### ISSUE TITLE
CopyFile.stage does not preserve execute permissions

### ISSUE THREAD

**Issue by timoreimann** [marcuslonnberg/sbt-docker#31]
When adding or staging files, set execute permissions (e.g., `chmod u+x`-like settings) are not preserved. This is because `sbt.IO`'s [copyFile](https://github.com/sbt/sbt/blob/127081b3c5af07058a88f0130e0cfd7fe0838e7a/util/io/src/main/scala/sbt/IO.scala#L580) method just copies file content. While there is a flag to preserve the last modified timestamp, nothing similar exists for execute permissions. For binaries/scripts copied into the Docker image, this is a problem.

I found [sbt upstream issue #713](https://github.com/sbt/sbt/issues/713) which addresses the issue. Unfortunately, the ticket has been marked as duplicate with no reference to the official issue, and I failed to find any other as well. Thus, I think it'd be best if sbt-docker would swap out the copy implementation by something that keeps execute permissions.

**Comment by h8** [comment]
Very annoying issue. Currently I used to add external system call to fix this.

**Comment by marcuslonnberg** [comment]
I have started working on a fix.

Currently regular java.io is used to copy files (by sbt) which ignores file permissions.
But java.nio have support for file permissions, which solves this problem.

This will make JDK 7 a minimum when building.
