### ISSUE TITLE
dockerBuildAndPush starts the app

### ISSUE THREAD

**Issue by Synesso** [marcuslonnberg/sbt-docker#32]
I'm not 100% sure about this, but it seems that when I run `sbt dockerBuildAndPush` the application starts. But if I run`sbt docker && sbt dockerPush` the app will not start. Is this correct? Is it intentional?

**Comment by Synesso** [comment]
Actually, it seems that the app starts with `sbt docker` or `sbt dockerBuildAndPush` and terminates when sbt does. How do I stop this behaviour? Is docker autorunning?

**Comment by marcuslonnberg** [comment]
I have not seen that behavior before.
How is your `dockerfile` setting and `docker` task defined?

**Comment by Synesso** [comment]
See
http://stackoverflow.com/questions/30770131/why-execute-application-on-docker-image-creation

**Comment by marcuslonnberg** [comment]
I can't see any problems with the config.
Does your application start when you run `sbt assembly`?

**Comment by Synesso** [comment]
No, sbt assembly doesn't start the app.

I _do_ have a file in the root of the project called Dockerrun.aws.json,
which contains:

{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "image/name",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": "8080"
    }
  ],
  "Authentication": {
    "Bucket": "bucketname",
    "Key": "key"
  }
}

Is that a clue?

**Comment by marcuslonnberg** [comment]
That file should not effect sbt-docker.

Can you show me your log for when you run `sbt docker`?

**Comment by Synesso** [comment]
Your request made me put my thinking cap on. I put a sleep in one of the specs and ran `sbt test`. I discovered that one of the specs was accidentally starting the app in the background. Only during dockerPush is sbt running long enough for it to have a significant memory and logging implication.

Thanks for your help in tracking this down & sorry for the noise.
