### ISSUE TITLE
possibility to update latest tag when executing docker command

### ISSUE THREAD

**Issue by mayacr86** [marcuslonnberg/sbt-docker#35]
The [sbt-native-packager](http://www.scala-sbt.org/sbt-native-packager/formats/docker.html#publishing-settings) provides a setting called *dockerUpdateLatest* which automatically updates the latest tag. Is there a way to simulate that behavior with your plugin?

For example, right now on my project I have something like:

<code>
    imageNames in docker := Seq(

        ImageName(
            namespace = Some(organization.value),
            repository = name.value,
            tag = Some(version.value)
        )
    )
</code>

that will generate the image with the corresponding version taken from the *version* value on the sbt file. 

How can I "tell" the plugin to also generate/update the "latest" tag?

Thanks!

**Comment by mayacr86** [comment]
I did a little hack, but not sure if this is the right way to do it:
<code>
imageNames in docker := Seq(
    
    ImageName(
        namespace = Some(organization.value),
        repository = name.value,
        tag = Some("latest")
    ),
    ImageName(
        namespace = Some(organization.value),
        repository = name.value,
        tag = Some(version.value)
    ))
</code>

**Comment by marcuslonnberg** [comment]
In sbt-docker you have full control over your image names / tags with the `imageNames` key.
All names from `imageNames` will be tagged to your image after a successful build.

Your "hack" is the correct way to do it.

You can write your image names like this if you feel like they are too long:
```scala
ImageName(s"${organization.value}/${name.value}:latest")
```

**Comment by mayacr86** [comment]
awesome! thanks
