### ISSUE TITLE
Docs for depending on package task causes sbt import error

### ISSUE THREAD

**Issue by blbradley** [marcuslonnberg/sbt-docker#36]
Hello! Thanks for the project. Saved me from writing bash.

I lost some time on using the docs for depending on the package task. Specifically, `docker <<= docker.dependsOn(`package`.in(Compile, packageBin))` throws an error:

```
Error:Error while importing SBT project:

[info] Loading project definition from /home/brandon/src/coins/kafka-cryptocoin/project
/home/brandon/src/coins/kafka-cryptocoin/docker.sbt:1: error: reference to package is ambiguous;
it is imported twice in the same scope by
import dsl._
and import Keys._
docker <<= docker.dependsOn(`package`.in(Compile, packageBin))
                            ^
[error] Type error in expression
```

The basic example worked fine. So, I followed it. Can we change the docs to follow the basic example? Confirm this, and I'll send a PR.

**Comment by marcuslonnberg** [comment]
Thanks for reporting this.
The example in `examples/package-basic/build.sbt` had the correct code, but the example in the README was incorrect.

**Comment by blbradley** [comment]
No problem!
