### ISSUE TITLE
sbt 'organization' not set builds image name that starts with 'default/'

### ISSUE THREAD

**Issue by blbradley** [marcuslonnberg/sbt-docker#37]
It looks like this was not the intent [here](https://github.com/marcuslonnberg/sbt-docker/blob/f1db3e818fcc65a1724e88b312aa8b955bef7e32/src/main/scala/sbtdocker/DockerSettings.scala#L44).

Does SBT set the organization name to 'default' by default? I did some searches but couldn't find anything.

**Comment by blbradley** [comment]
Can confirm sbt has a default organization with value 'default'.

```
[info] Loading project definition from /home/brandon/src/coins/kafka-cryptocoin/project
[info] Set current project to kafka-cryptocoin (in build file:/home/brandon/src/coins/kafka-cryptocoin/)
[info] Setting: java.lang.String = default
[info] Description:
[info]  Organization/group ID.
[info] Provided by:
[info]  {file:/home/brandon/src/coins/kafka-cryptocoin/}kafka-cryptocoin/*:organization
[info] Defined at:
[info]  (sbt.Classpaths) Defaults.scala:1107
[info]  (sbt.Build) Build.scala:57
[info] Dependencies:
[info]  *:normalizedName
[info]  *:thisProject
[info] Reverse dependencies:
[info]  *:projectId
[info]  *:docker::imageName
[info]  *:organizationName
[info] Delegates:
[info]  *:organization
[info]  {.}/*:organization
[info]  */*:organization
```

**Comment by marcuslonnberg** [comment]
`organization` seems to default to the value `default` when `name` is not set. But if `name` is set, then `organization` will get its value.
https://github.com/sbt/sbt/blob/v0.13.9/main/src/main/scala/sbt/Defaults.scala#L1107

What is your use case for this?
I am not sure this is something that needs to be fixed.
In most cases you should set your image names with `imageNames`, then it can be any name you want.

**Comment by blbradley** [comment]
I had name set, but organization was 'default'.

I don't have a particular use case myself, but there could be users that may not want to specify 'organization' for a private Docker registry.

No worries if you don't want to change it.

**Comment by marcuslonnberg** [comment]
Ok I see.

I think we can ignore this.
If someone doesn't want to set `organization` then they can easily set the image name for their Docker image with:
```scala
imageNames in docker := Seq(
  ImageName(s"${name.value}:version")
)
```
