### ISSUE TITLE
Passing arguments using entryPointShell broken

### ISSUE THREAD

**Issue by l15k4** [marcuslonnberg/sbt-docker#38]
Hi,

I cannot find a way how to properly pass arguments using `entryPointShell`. For instance :
```
entryPointShell("java", "-jar", "my.jar", "$@")
docker run --rm my-image foo bar baz
```
Looses the first `foo` argument, only `bar baz` come through.

```
entryPointShell("java", "-jar", "my.jar")
docker run --rm my-image foo bar baz
```
Doesn't pass any argument at all.

I tried many more other combinations but nothing does it. Could you please help me out here? Note that I need shell here cause I'm passing also env variables in there.

**Comment by marcuslonnberg** [comment]
I think this is a general Docker issue, not specific to sbt-docker.

You can look at the Dockerfile that sbt-docker generates in `target/docker/Dockerfile`.
The entrypoint instruction should look something like this:
```
ENTRYPOINT java -jar my.jar $@
```

$@ only contains arguments 1 to n. You need to include $0 to $n, for example with $0 $@.

**Comment by l15k4** [comment]
I see, so the solution is : 
```
entryPointShell("java", "$JAVA_OPTS", "-jar", "my.jar", "$0", "$@")
```

Considering that `$JAVA_OPTS` is the reason I wanted to do that.  I finally used `-e JAVA_TOOL_OPTIONS`.

> $@ only contains arguments 1 to n. You need to include $0 to $n, for example 

How come? `$0` expands to the name of the shell or shell script... `1 to n` should be correct.

**Comment by marcuslonnberg** [comment]
In this case with entrypoint in Docker, `$0` will be the first argument that you pass in.
I don't know the reason for this.
