### ISSUE TITLE
`docker tag -f` deprecated in docker 1.10

### ISSUE THREAD

**Issue by sherzberg** [marcuslonnberg/sbt-docker#39]
You can now leave off the `-f` when tagging as it overwrites the previous no matter what. https://docs.docker.com/engine/deprecated/. Currently this just throws a warning, but soon will be removed.

https://github.com/marcuslonnberg/sbt-docker/blob/master/src/main/scala/sbtdocker/DockerTag.scala#L17

I don't see a supported docker version list. Thoughts on how to support the flag for older versions of Docker as well as newer?

**Comment by kurtkopchik** [comment]
I agree, it would be great if the plug-in supported the v1.12 Docker release which aims to remove this flag as well as the previous versions that do support it. Currently, it appears that sbt-docker will stop working once v.1.12 of Docker is released.

**Comment by kurtkopchik** [comment]
FYI @sherzberg I submitted a [pull request](https://github.com/marcuslonnberg/sbt-docker/pull/46) with a fix for this issue.

**Comment by marcuslonnberg** [comment]
Will release a new version later today with #46 included.

**Comment by marcuslonnberg** [comment]
Version 1.4.0 have now been released.
