### ISSUE TITLE
CHANGELOG stuck at 1.0.0

### ISSUE THREAD

**Issue by timoreimann** [marcuslonnberg/sbt-docker#40]
While I do see updates in the `notes/` directory, they don't seem to be reflected in the CHANGELOG anymore: The latest entry is for 1.0.0.

Can we possibly bring the CHANGELOG up-to-date?

Thanks!

**Comment by marcuslonnberg** [comment]
The `CHANGELOG.md` is now up to date.

Thanks for reporting!
