### ISSUE TITLE
Dokerfile

### ISSUE THREAD

**Issue by mrsanuk** [marcuslonnberg/sbt-docker#41]
Hi, I have a question, 
I use sbt+docker and by default, have dokerfile:

FROM java
WORKDIR /opt/docker
ADD opt /opt
RUN ["chown", "-R", "daemon:daemon", "."]
USER daemon
ENTRYPOINT ["bin/script_name"]
CMD []

How to modify "ENTRYPOINT ["bin/script_name"]" section to  "ENTRYPOINT ["bin/script_name   -Dcom.sun.management.jmxremote   -Dcom.sun.management.jmxremote.port=9999"] "

I tryed add to build.sbt a line "dockerEntrypoint := "/bin/script_name   -Dcom.sun.management.jmxremote   -Dcom.sun.management.jmxremote.port=9999"", but had no result

Thanks

**Comment by marcuslonnberg** [comment]
Looks like you are using sbt-native-packager since you have `dockerEntrypoint`. Ask for help there instead.
