### ISSUE TITLE
var in from instruction

### ISSUE THREAD

**Issue by stannie42** [marcuslonnberg/sbt-docker#45]
When using a var in from instruction in a Build.scala file, the var isn't replaced by its value.

e.g from("java:${javaVersion}") will end in
[info] Step 1 : FROM java:${javaVersion}

Is it the expected behaviour?

Thanks,
Pierre.

**Comment by marcuslonnberg** [comment]
In your example it looks like you are missing the **s** before the string in `from("java:${javaVersion}")`.
It should be `from(s"java:${javaVersion}")` if you want to use string interpolation.

**Comment by stannie42** [comment]
Indeed ! Thanks :)
