### ISSUE TITLE
How to copy file from main dir

### ISSUE THREAD

**Issue by elmalto** [marcuslonnberg/sbt-docker#50]
Hi,

how do I copy a file from the main dir (same as build.sbt) to the docker container?

```
dockerfile in docker := {
  val artifact: File = assembly.value
  val artifactTargetPath = s"/app/${artifact.name}"
  new Dockerfile {
    from("java:openjdk-8u91-jre")
    add(artifact, artifactTargetPath)
    addRaw("production.conf","/app/production.conf")
    entryPoint("java", "-jar","-Dconfig.resource=/app/production.conf", artifactTargetPath)
  }
}
```

returns the error

```
[info] Step 3 : ADD production.conf /app/production.conf
[info] lstat production.conf: no such file or directory
```

**Comment by elmalto** [comment]
ok sorry about this :)

```
copy(baseDirectory(_ / "production.conf" ).value,"/app/production.conf")
```

**Comment by wulftone** [comment]
Thanks this saved me.. spent an hour trying to figure out how to `copy` a directory of files into the docker image.  Those strange `baseDirectory` dirs are.... strange.  Is there a way to make that transparent so we don't have to know about that?

**Comment by robbyki** [comment]
Similarly, trying to copy directory contents from a root level location same level as `build.sbt` but this didn't work for me. something along these lines. Running this from a module within root level. 
```
copyRaw(baseDirectory(_ / "spark-2.4.1-bin-hadoop2.7/jars") , "/opt/spark/jars")
```
