### ISSUE TITLE
Use a Dockerfile

### ISSUE THREAD

**Issue by jonbjo** [marcuslonnberg/sbt-docker#56]
Is it possible to use a Dockerfile similar to how it is done in e.g. https://github.com/spotify/docker-maven-plugin#use-a-dockerfile? If not, are there any plans to add that support?

**Comment by marcuslonnberg** [comment]
Right now it isn't supported.
Can you please tell me about your use case for this compared to using the DSL?

I'm working a few big changes now. Will consider supporting this.

**Comment by jonbjo** [comment]
Those who are working in both maven and sbt will get a more similar experience moving between the two. For simpler use cases having a static Dockerfile is easier to grasp and especially those new to sbt, the threshold will be lower to get started. Personally I also prefer having the Dockerfile visible in the repo rather than via DSL in build.sbt. 

If you decide to support this, what would the E.T.A. be?

**Comment by devshorts** [comment]
I'm with @jonbjo here. It would be great to have this option.  I find that for more complicated dockerfiles its easier to manage in a separate file instead of using the docker dsl.

**Comment by liu0013** [comment]
+1

**Comment by andyfr** [comment]
I would like to reference dockerfiles in docker-compose.
With the current solution i have to maintain the dockerfile for compose and the dsl in sbt.

**Comment by nsauro** [comment]
+1

**Comment by petewilcock** [comment]
+1

**Comment by robertomoreno** [comment]
+1

**Comment by julianheres** [comment]
+1

**Comment by jimenefe** [comment]
+1

**Comment by M1123581E** [comment]
+1

**Comment by vicchugu** [comment]
+1

**Comment by matzoon** [comment]
+1

**Comment by barambani** [comment]
+1, thanks

**Comment by Gassa** [comment]
+1

**Comment by devsaik** [comment]
+1

**Comment by AlexTawse** [comment]
+1

**Comment by QingWenYe** [comment]
+1, thanks

**Comment by marcuslonnberg** [comment]
This is now supported in version 1.6.0.

Use the following in your build configuration:
```scala
dockerfile in docker := NativeDockerfile(file("subdirectory") / "Dockerfile")
```
