### ISSUE TITLE
Docker task fails with latest Docker for OSX

### ISSUE THREAD

**Issue by RomanIakovlev** [marcuslonnberg/sbt-docker#64]
When running current Docker version (17.03.0-ce) on OSX, the following errors shows up when running the `docker` task:

```
[error] (awesome_software/*:docker) Could not parse Version from 17.03.0-ce
[error] : `.' expected but `3' found
```

This is most probably caused by new version format, introduced together with Docker Community Edition (whatever this means).

**Comment by james-turner** [comment]
+1

**Comment by shiv4nsh** [comment]
+1

**Comment by marcuslonnberg** [comment]
Looks like same problem as #60. Should already be fixed.

**Comment by RomanIakovlev** [comment]
Oops, I've somehow missed the existent issue. Sorry!
