### ISSUE TITLE
Problems with docker 1.17.0-ce

### ISSUE THREAD

**Issue by kufi** [marcuslonnberg/sbt-docker#66]
The plugin has problems with the latest docker releases, as they report a version in the format "1.17.0-ce", which cannot be parsed by the Regex in Docker-Version:

https://github.com/marcuslonnberg/sbt-docker/blob/2bb33d1b4525b60c0b0151ac0bb2a706b3c399ea/src/main/scala/sbtdocker/DockerVersion.scala

The regex assumes a version in the format 1.13.0 (three whole numbers), but the new releases seem to add a -ce to the end, which breaks all builds on the current version.

**Comment by marcuslonnberg** [comment]
Are you using the latest version?

**Comment by kufi** [comment]
No, 1.4.0. Just seen that there is a new update out.
Sorry for the inconvenience.
