### ISSUE TITLE
Cannot find or load main class Docker

### ISSUE THREAD

**Issue by DDDFan** [marcuslonnberg/sbt-docker#67]
Hey there, 

not sure, if it belongs here, but i got an issue, that when i pack my Akka project into a docker image, it cannot find the main class when running the docker image. Are there any known  problems like this or workarounds? 

Thanks in advance!

**Comment by marcuslonnberg** [comment]
Please check the settings of the plugin that you are using to package your JVM application, such as `sbt-assembly` or `sbt-native-packager`. `sbt-docker` is only responsible for building the Docker image and your built application is just an input to that.
