### ISSUE TITLE
executable in javaOption during entrypoint command

### ISSUE THREAD

**Issue by robertomoreno** [marcuslonnberg/sbt-docker#70]
I'm generating the following Dockerfile:
```
dockerfile in docker := {
  val artifact: File = assembly.value
  val artifactTargetPath = s"/app/${artifact.name}"

  val ipCMD = "/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'"

  new Dockerfile {
    from(image)
    add(artifact, artifactTargetPath)
    expose(ports: _*)
    entryPoint("java", "-jar",
      "-Dbind-hostname=$(" + ipCMD + ")",
      artifactTargetPath)
  }
```

As you can see I'm trying to retrieve the container ip which will be saved in the `ipCMD` var. This will generate a jar command as 
```
java -jar -Dbind-hostname=`/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'` /app/wws-renditions-coordinator.jar
```
which is Ok, but when run the content **the property will receive the command as value** so the value of the property `bind-hostname` is `$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')` **not the expected ip**. I have checked this **working in a Dockerfile**. If it is used an `entryPointRaw` command as follows, it **works**:
```
entryPointRaw("java -jar -Dbind-hostname=$(" + ipCMD + ") "+artifactTargetPath)
```

**UPDATE**
After moving forward I've realised that to use entryPointRaw is not the best work around since it not allows you to pass extra arguments to the main class. It is easier just to add an shell script as a runner with all the needed operations.

**Comment by marcuslonnberg** [comment]
To get a environment variable you need to execute your command in a shell.
`entryPoint()` uses the "exec form" which runs the command directly (see <https://docs.docker.com/engine/reference/builder/#entrypoint>).
`entryPointShell()` uses the "shell form". Which I think should work for you.
