### ISSUE TITLE
add network to BuildOptions

### ISSUE THREAD

**Issue by MasseGuillaume** [marcuslonnberg/sbt-docker#74]
This is the man page for the build command: https://docs.docker.com/edge/engine/reference/commandline/build/

setting --network=host can speed up the build speed.

**Comment by MasseGuillaume** [comment]
another way to do it would be via the java client: https://static.javadoc.io/com.spotify/docker-client/8.8.4/index.html

**Comment by jiminhsieh** [comment]
I think I could give this a shot. I could do it similar to `BuildOptions.Remove` and `BuildOptions.Pull`. However, I don't know is it a good idea to use Spotify's docker client here. Since the design of docker client is to send request to Docker's API. sbt-docker is to execute command locally. sbt-docker uses a different approach with docker client.

**Comment by marcuslonnberg** [comment]
@jiminhsieh A while back I started to experiment with Spotify's client. It is available in the `refactoring` branch if you want to have a look at it. Should be fairly functional. But I ran in to some weird bugs that I haven't had time to look into properly yet.

**Comment by jiminhsieh** [comment]
@marcuslonnberg I see. I will take a look at it. But do you remember what kind of wired bugs? Thanks! :)

**Comment by jiminhsieh** [comment]
@marcuslonnberg I did some experiments with `docker-client 8.9.1`, `docker-client 8.7.2` and `docker 17.09.0-ce-mac35`. I didn't encounter any issue. If you don't mind, I could send a WIP-PR to `refactoring` branch latter to let you see. Or if you have more information about those wired bugs to share, I can investigate more. Thanks! :)

**Comment by OlegYch** [comment]
there are many other options currently missing, i'd suggest allowing raw string options

**Comment by marcuslonnberg** [comment]
Support for this have been added in `BuildOptions.additionalArguments` in https://github.com/marcuslonnberg/sbt-docker/releases/tag/v1.8.0.
