### ISSUE TITLE
Add --cache-from support.

### ISSUE THREAD

**Issue by htmldoug** [marcuslonnberg/sbt-docker#81]
docker builds on different machines (or after clearing the docker cache) do not reuse the build cache (as of 1.10 for security reasons). A new mechanism, `--cache-from`, was added in 1.13 to restore the capability.

* https://blog.nimbleci.com/2016/11/17/whats-coming-in-docker-1-13/#cache-layers-when-building
* https://github.com/moby/moby/issues/20316

In order to reuse the build cache of an older image,
1. old image must be in the local cache, e.g. with `docker pull oldimage`
2. docker build must use the --cache-from arg, e.g. `docker build --cache-from oldimage .`

This is important for us since our builds often happen on different jenkins workers.

I'd like a way to either specify:
1. --cache-from images to be pulled and built, e.g.
```scala
case class CacheFromImage(name: String, pullFirst: Boolean = true)
val cacheFromImages: TaskKey[Seq[CacheFromImage]] = ...
```
2. specify build args to pass to the docker process:
```scala
dockerBuildArgs := dockerBuildArgs.value ++ Seq("--cache-from", image1, "--cache-from", image2)
```

**Comment by marcuslonnberg** [comment]
Support for this have been added in `BuildOptions.additionalArguments` in https://github.com/marcuslonnberg/sbt-docker/releases/tag/v1.8.0.
