### ISSUE TITLE
How to copy all the files from source folder to target inside Docker image

### ISSUE THREAD

**Issue by AbacusIntegrationPlatform** [marcuslonnberg/sbt-docker#85]
I have all my files inside src/main/resources folder in source. I want to have all the files inside resources inside src/main/resources/ inside the container. 
I tried the below way, but not working -

 new Dockerfile {
   from("base-image")
   add(artifact, artifactTargetPath)
   copy(baseDirectory(_ / "src" / "main" / "resources" / * ).value, "/src/main/resources/")
   entryPoint("sh","-c","java -jar $JAVA_OPTIONS"+artifactTargetPath)

What is the right way of doing this ?
All the files inside resources has to be moved to target.

**Comment by jpzk** [comment]
I have the same problem ...

**Comment by AbacusIntegrationPlatform** [comment]
The src/main/resources/ folder in the code comprise of bunch of folders and files inside it.
For example -
src/main/resources/ the below folder structure is there -
![image](https://user-images.githubusercontent.com/29430500/44701548-dafe5d00-aaac-11e8-89ea-4ccfe7fa8d7d.png)

And inside each folder the below files are there -
![image](https://user-images.githubusercontent.com/29430500/44701560-ece00000-aaac-11e8-954b-8457122fef03.png)

The need is to copy the entire content of "resources" inside the container /src/main/resources/ folder.
Currently as a work around i am achieving this by using a Dockerfile after sbt assembly.
Docker file command - `COPY src/main/resources/ /src/main/resources/`
What is the way of doing the same using the plugin.

**Comment by marcuslonnberg** [comment]
If this line
```scala
copy(baseDirectory(_ / "src" / "main" / "resources" / * ).value, "/src/main/resources/")
```
is calling `copy(String, String)` then it is deprecated call which is equivalent to `copyRaw(String, String)`. Instead `copy(java.io.File, String)` should be used to get the desired behaviour.

Also which version of the plugin is used and which version of sbt?

**Comment by jpzk** [comment]
@marcuslonnberg 
copy(baseDirectory(_ / "src" / "main" / "resources" / "logback.xml" ).value, "/src/main/resources/")
I did this now and it worked. I used add and addRaw which didn't work. :)

**Comment by jpzk** [comment]
@AbacusIntegrationPlatform with * it didn't work for me but explicitly stating the filenames worked.
