### ISSUE TITLE
Setting Environment Variables

### ISSUE THREAD

**Issue by kterusaki** [marcuslonnberg/sbt-docker#97]
We're trying to set an environment variable for the docker container. Below is our docker configuration:

```
dockerfile in docker := {
  new Dockerfile {
    val dockerAppPath = "/app/"
    val mainClassString = (mainClass in Compile).value.get
    val classpath = (fullClasspath in Compile).value
    from("java")
    add(classpath.files, dockerAppPath)
    env("ENVIRONMENT", "test")
    entryPoint("java", "-cp", s"$dockerAppPath:$dockerAppPath/*", s"$mainClassString")
  }
}
```

The resulting Dockerfile that's generated in the target directory contains the following command

`ENV ENVIRONMENT="test"`

But our application running within the container doesn't seem to be picking it up. When we set this environment locally, it does work though.

We're using sbt-docker-compose in conjuction with sbt-docker to run integration tests.

**Comment by marcuslonnberg** [comment]
Please have a look at the following example https://github.com/marcuslonnberg/sbt-docker/blob/master/src/sbt-test/sbt-docker/environment-variable/build.sbt. If there is still an issue please reopen the issue.
